# Generated by Django 4.2 on 2023-04-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("info", "0016_auto_20210820_1553"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
